 BaseURL = "https://jayleen.info"
  languageCode = "en-us"
  defaultContentLanguage = "en"
  baseURL = "/"
  title = "Jayleen Serrano"
  relativeURLS = true

  [taxonomies]
  tag = "tags"

  [permalinks]
  post = "/:title/"
  issues = "/:sections[1:]/:title"

  [params]
  author = ""
  description = "Jayleen makes things."

      
 [frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
